export const countries = [
  { code: "SA", name: "Saudi Arabia", nameAr: "المملكة العربية السعودية", dial: "+966" },
  { code: "AE", name: "United Arab Emirates", nameAr: "الإمارات العربية المتحدة", dial: "+971" },
  { code: "EG", name: "Egypt", nameAr: "مصر", dial: "+20" },
  { code: "JO", name: "Jordan", nameAr: "الأردن", dial: "+962" },
  { code: "KW", name: "Kuwait", nameAr: "الكويت", dial: "+965" },
  { code: "QA", name: "Qatar", nameAr: "قطر", dial: "+974" },
  { code: "BH", name: "Bahrain", nameAr: "البحرين", dial: "+973" },
  { code: "OM", name: "Oman", nameAr: "عُمان", dial: "+968" },
  { code: "LB", name: "Lebanon", nameAr: "لبنان", dial: "+961" },
  { code: "IQ", name: "Iraq", nameAr: "العراق", dial: "+964" },
  { code: "US", name: "United States", nameAr: "الولايات المتحدة", dial: "+1" },
  { code: "GB", name: "United Kingdom", nameAr: "المملكة المتحدة", dial: "+44" },
  { code: "CA", name: "Canada", nameAr: "كندا", dial: "+1" },
  { code: "AU", name: "Australia", nameAr: "أستراليا", dial: "+61" },
  { code: "DE", name: "Germany", nameAr: "ألمانيا", dial: "+49" },
  { code: "FR", name: "France", nameAr: "فرنسا", dial: "+33" },
  { code: "TR", name: "Turkey", nameAr: "تركيا", dial: "+90" },
  { code: "IN", name: "India", nameAr: "الهند", dial: "+91" },
  { code: "PK", name: "Pakistan", nameAr: "باكستان", dial: "+92" },
  { code: "MA", name: "Morocco", nameAr: "المغرب", dial: "+212" },
];
